### PR TITLE
update with ti-commits up to v5.7.0

### PR DESCRIPTION
**Pull request by orgua**
I don't know how helpful this merge was. The new code is probably incompatible with gcc. But i want to leave this PR here for documentation.

The main ``/include`` or ``/lib`` didn't change from v4.0 to v5.7 that much for the am335x: some new drivers, extended comments and codestyle. 
For the AM335x-Include there are new drivers: 
- mcspi.h
- tscAdcSs.h

Mainly the examples got improved over the years

I used these instructions: http://www.bartread.com/2014/02/12/git-basics-how-to-merge-changes-from-a-different-fork-into-your-own-branch/

### CODE REVIEW

**Comment by dinuxbg** [comment]
@orgua , which examples did you test?

**Comment by dinuxbg** [comment]
> I don't know how helpful this merge was. The new code is probably incompatible with gcc. But i want to leave this PR here for documentation.

I don't think merge is the correct strategy. TI has made too many reorganizations, including whitespace changes. I would suggest to rebase (or cherry-pick) the GCC enablement patches on top of latest TI code. This way it would be much easier to review the update.

If you do get to a working state than please let me know. Having a tested GIT tree is always good to have  as a reference.

**Comment by orgua** [comment]
Yeah, you are probably right. Your changes looked huge in the beginning, but there are only some lines to adapt... 

I work with this branch for some weeks now. no examples, but a fairly extensive codebase using both PRUs and some hardware modules: sys_spi, pru_intc, pru_iep, pru_rpmsg, virtqueue.

for the most part the project still uses cgt with make because cmake issues gcc-linker-problems, but gcc is compiling! 

I think TI is open for pull requests and even for discussions about adding gcc-support to the library. When I finish my work and still have time I will initiate the discussion. I began to extend and optimize the support package, would be a shame not contributing the changes.

**Comment by dinuxbg** [comment]
> I think TI is open for pull requests and even for discussions about adding gcc-support to the library.

That would be awesome. Maintaining and constantly rebasing a fork is seldom a fun exercise.

Let me know if you need help for something.

**Pull request closed without merging**
